CREATE TYPE gametypes AS ENUM ('TEKKEN_7', 'SFV', 'STREET_FIGHTER_6','KOF_XV', 'GUILTY_GEAR_STRIVE', 'TEKKEN_8', 'MORTAL_KOMBAT_1')
CREATE TYPE mailstatustypes AS ENUM ('SENT', 'ERROR')
CREATE TYPE userverificationtypes AS ENUM ('PASSWORD_CHANGE', 'EMAIL_VERIFICATION')
CREATE TYPE oauthtypes AS ENUM ('GOOGLE');