import { ComboStepTranslation } from '../types/combo-translation';

export const TEKKEN_7_COMBO_MAP = {
  F: 'FORWARD',
  N: 'NEUTRAL',
  D: 'DOWN',
  B: 'BACK',
  DF: 'BACK-FORWARD',
  DB: 'DOWN-BACK',
  UF: 'UP-FORWAD',
  UB: 'UP-BACK',
  BF: 'BACK-FORWARD',
  FB: 'FORWARD-BACK',
  'S!': 'SCREW',
  FC: 'FULL-CROUCH',
  QCF: 'QUARTER CIRCLE FORWARD',
  QCB: 'QUARTER CIRCLE BACK',
  CH: 'COUNTER-HIT',
  HCF: 'HALF CIRCLE FORWARD',
  HCB: 'HALF CIRCLE BACK',
  CD: 'CROUCH DASH',
  SS: 'SIDE STEP',
  SSR: 'SIDE STEP RIGHT',
  SSL: 'SIDE STEP LEFT',
  SWL: 'SIDE WALK LEFT',
  SWR: 'SIDE WALK RIGHT',
  WR: 'WHILE RUNNING',
  WS: 'WHILE STANDING',
  '2': 'TRIANGLE',
  '1': 'SQUARE',
  '3': 'CROSS',
  '4': 'CIRCLE',
} as const;

export type Tekken7MapType = keyof typeof TEKKEN_7_COMBO_MAP;

export const TEKKEN_7_COMBO_MAP_TRANSLATION: {
  [x: string]: ComboStepTranslation;
} = {
  F: { imagePath: '', action: TEKKEN_7_COMBO_MAP.F },
  N: { imagePath: '', action: TEKKEN_7_COMBO_MAP.N },
  D: { imagePath: '', action: TEKKEN_7_COMBO_MAP.D },
  B: { imagePath: '', action: TEKKEN_7_COMBO_MAP.B },
  DF: { imagePath: '', action: TEKKEN_7_COMBO_MAP.DF },
  DB: { imagePath: '', action: TEKKEN_7_COMBO_MAP.DB },
  UF: { imagePath: '', action: TEKKEN_7_COMBO_MAP.UF },
  UB: { imagePath: '', action: TEKKEN_7_COMBO_MAP.UB },
  BF: { imagePath: '', action: TEKKEN_7_COMBO_MAP.BF },
  FB: { imagePath: '', action: TEKKEN_7_COMBO_MAP.FB },
  'S!': { imagePath: '', action: TEKKEN_7_COMBO_MAP['S!'] },
  FC: { imagePath: '', action: TEKKEN_7_COMBO_MAP.FC },
  QCF: { imagePath: '', action: TEKKEN_7_COMBO_MAP.QCF },
  QCB: { imagePath: '', action: TEKKEN_7_COMBO_MAP.QCB },
  CH: { imagePath: '', action: TEKKEN_7_COMBO_MAP.CH },
  HCF: { imagePath: '', action: TEKKEN_7_COMBO_MAP.HCF },
  HCB: { imagePath: '', action: TEKKEN_7_COMBO_MAP.HCB },
  CD: { imagePath: '', action: TEKKEN_7_COMBO_MAP.CD },
  SS: { imagePath: '', action: TEKKEN_7_COMBO_MAP.SS },
  SSR: { imagePath: '', action: TEKKEN_7_COMBO_MAP.SSR },
  SSL: { imagePath: '', action: TEKKEN_7_COMBO_MAP.SSL },
  SWL: { imagePath: '', action: TEKKEN_7_COMBO_MAP.SWL },
  SWR: { imagePath: '', action: TEKKEN_7_COMBO_MAP.SWR },
  WR: { imagePath: '', action: TEKKEN_7_COMBO_MAP.WR },
  WS: { imagePath: '', action: TEKKEN_7_COMBO_MAP.WS },
  1: { imagePath: '', action: TEKKEN_7_COMBO_MAP[1] },
  2: { imagePath: '', action: TEKKEN_7_COMBO_MAP[2] },
  3: { imagePath: '', action: TEKKEN_7_COMBO_MAP[3] },
  4: { imagePath: '', action: TEKKEN_7_COMBO_MAP[4] },
} as const;
