export const STREET_FIGHTER_6_COMBO_MAP = {
  U: 'UP',
  F: 'FORWARD',
  B: 'BACK',
  S: 'STANDING',
  C: 'CROUCHING',
  D: 'DOWN',
  J: 'JUMPING',
  DF: 'DOWN-FORWARD',
  DB: 'DOWN-BACK',
  UF: 'UP-FORWAD',
  UB: 'UP-BACK',
  QCF: 'QUARTER CIRCLE FORWARD',
  QCB: 'QUARTER CIRCLE BACK',
  CH: 'COUNTER-HIT',
  HCF: 'HALF CIRCLE FORWARD',
  HCB: 'HALF CIRCLE BACK',
  P: 'PUNCH',
  PPP: 'ALL PUNCHES',
  K: 'KICK',
  KKK: 'ALL KICKS',
  LP: 'LIGHT PUNCH',
  MP: 'MEDIUM PUNCH',
  HP: 'HEAVY PUNCH',
  LK: 'LIGHT KICK',
  MK: 'MEDIUM KICK',
  HK: 'HEAVY KICK',
  XX: 'SPECIAL CANCEL',
  DI: 'DRIVE IMPACT',
  DRC: 'DRIVE RUSH CANCEL',
} as const;

export type StreetFighter6MapKey = keyof typeof STREET_FIGHTER_6_COMBO_MAP;

export const STREET_FIGHTER_6_COMBO_MAP_TRANSLATION = {
  S: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.S,
  },
  C: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.C,
  },
  J: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.J,
  },
  F: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.F,
  },
  U: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.U,
  },
  D: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.D,
  },
  B: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.B,
  },
  DF: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.DF,
  },
  DB: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.DB,
  },
  UF: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.UF,
  },
  UB: {
    imagePath: '',
    action: STREET_FIGHTER_6_COMBO_MAP.UB,
  },
  QCF: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.QCF },
  QCB: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.QCB },
  CH: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.CH },
  HCF: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.HCF },
  HCB: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.HCB },
  K: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.K },
  P: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.P },
  PPP: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.PPP },
  KKK: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.KKK },
  LP: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.LP },
  MP: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.MP },
  HP: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.HP },
  LK: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.LK },
  HK: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.HK },
  MK: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.MK },
  XX: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.XX },
  DRC: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.DRC },
  DI: { imagePath: '', action: STREET_FIGHTER_6_COMBO_MAP.DI },
} as const;
