.env:
  prefix: ""

authentication:
  auth:
    secureKey: ${SECURE_KEY}
    secureToken: ${SECURE_TOKEN:true}
    tokenExpirationMsec: ${TOKEN_EXPIRATION_MSEC}
    tokenSecret: ${TOKEN_SECRET}
    refreshTokenExpirationMsec: ${REFRESH_TOKEN_EXPIRATION_MSEC}

email-verification:
  base-frontend-url: ${BASE_EMAIL_VERIFICATION_FRONTEND_URL}
password-change:
  base-frontend-url: ${BASE_PASSWORD_CHANGE_FRONTEND_URL}

logging:
  level:
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    org:
      hibernate:
        type: TRACE

management:
  defaults:
    metrics:
      export:
        enabled: false
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_MAIL_USERNAME}
    password: ${MAIL_SENDER_MAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  application:
    name: fgc-combo-companion
  datasource:
    url: ${POSTGRESQL_CONNECTION}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
    hikari:
      max-lifetime: 500000 #~8minutes
      idle-timeout: 300000
      maximum-pool-size: 15
      minimum-idle: 15
      pool-name: fgc-api
  flyway:
    baselineOnMigrate: true
    url: ${POSTGRESQL_CONNECTION}
    user: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
