.env:
  prefix: ""
logging:
  level:
    org:
      hibernate:
        type: TRACE

email-verification:
  base-user-email-verification-frontend-url: ${BASE_USER_EMAIL_VERIFICATION_FRONTEND_URL}
management:
  endpoints:
    jmx:
      exposure:
        include: "*"
authentication:
  auth:
    secureToken: ${SECURE_TOKEN:true}
    tokenExpirationMsec: ${TOKEN_EXPIRATION_MSEC}
    tokenSecret: ${TOKEN_SECRET}
    refreshTokenExpirationMsec: ${REFRESH_TOKEN_EXPIRATION_MSEC}
    accessTokenCookieName: accessToken
    refreshTokenCookieName: refreshToken

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_MAIL_USERNAME}
    password: ${MAIL_SENDER_MAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  application:
    name: template
  datasource:
    url: ${AUTH_SERVICE_POSTGRESQL_CONNECTION}
    username: ${AUTH_SERVICE_POSTGRESQL_USERNAME}
    password: ${AUTH_SERVICE_POSTGRESQL_PASSWORD}
  flyway:
    baselineOnMigrate: true
    url: ${AUTH_SERVICE_POSTGRESQL_CONNECTION}
    user: ${AUTH_SERVICE_POSTGRESQL_USERNAME}
    password: ${AUTH_SERVICE_POSTGRESQL_PASSWORD}
