.env:
  prefix: ""

authentication:
  auth:
    secureToken: ${SECURE_TOKEN:true}
    tokenExpirationMsec: ${TOKEN_EXPIRATION_MSEC}
    tokenSecret: ${TOKEN_SECRET}
    refreshTokenExpirationMsec: ${REFRESH_TOKEN_EXPIRATION_MSEC}

email-verification:
  base-frontend-url: ${BASE_EMAIL_VERIFICATION_FRONTEND_URL}
password-change:
  base-frontend-url: ${BASE_PASSWORD_CHANGE_FRONTEND_URL}

logging:
  level:
    org:
      hibernate:
        type: TRACE

management:
  endpoints:
    jmx:
      exposure:
        include: "*"
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SENDER_MAIL_USERNAME}
    password: ${MAIL_SENDER_MAIL_PASSWORD}
    properties:
      smtp:
        auth: true
        starttls:
          enable: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  application:
    name: template
  datasource:
    url: ${POSTGRESQL_CONNECTION}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
  flyway:
    baselineOnMigrate: true
    url: ${POSTGRESQL_CONNECTION}
    user: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}
